site_name: RVN Client Analysis Tool
site_description: Documentation for the RVN Client Analysis Tool
site_author: Reuters
copyright: '&copy; Reuters 2025'

repo_url: https://github.com/reuters/rvn-client-analysis-tool
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Typography Guide: typography.md
  - Branding Guide: branding.md
  - Recent Updates: recent_updates.md
  - Project README: https://github.com/reuters/rvn-client-analysis-tool/blob/main/README.md

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/reuters
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/reuters
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/reuters
